const CONFIG = {
  "nombreLocal": "Aries Drinks",
  "telefono": "5493564205207",
  "passwordAdmin": "admin123",
  "zonasEnvio": [
    {
      "nombre": "20 de Junio",
      "precio": 4000
    },
    {
      "nombre": "9 de Septiembre",
      "precio": 3000
    },
    {
      "nombre": "Bouchard",
      "precio": 3000
    },
    {
      "nombre": "Brisas del Sur",
      "precio": 3000
    },
    {
      "nombre": "Casonas del Bosque",
      "precio": 5000
    },
    {
      "nombre": "Catedral",
      "precio": 3000
    },
    {
      "nombre": "Consolata",
      "precio": 3000
    },
    {
      "nombre": "Corradi",
      "precio": 4000
    },
    {
      "nombre": "Cottolengo",
      "precio": 4000
    },
    {
      "nombre": "Dos Hermanos",
      "precio": 4000
    },
    {
      "nombre": "El Prado",
      "precio": 5000
    },
    {
      "nombre": "General Savio",
      "precio": 5000
    },
    {
      "nombre": "Hospital",
      "precio": 4000
    },
    {
      "nombre": "Independencia",
      "precio": 4000
    },
    {
      "nombre": "Iturraspe",
      "precio": 3000
    },
    {
      "nombre": "Jardín",
      "precio": 3000
    },
    {
      "nombre": "José Hernández",
      "precio": 5000
    },
    {
      "nombre": "La Arbolada I",
      "precio": 5000
    },
    {
      "nombre": "La Arbolada II",
      "precio": 5000
    },
    {
      "nombre": "La Florida",
      "precio": 5000
    },
    {
      "nombre": "La Milka",
      "precio": 3000
    },
    {
      "nombre": "Las Rosas",
      "precio": 4000
    },
    {
      "nombre": "Loteo Magdalena",
      "precio": 5000
    },
    {
      "nombre": "Maipú",
      "precio": 5000
    },
    {
      "nombre": "Palmares",
      "precio": 5000
    },
    {
      "nombre": "Parque Industrial",
      "precio": 4000
    },
    {
      "nombre": "Plaza San Francisco",
      "precio": 5000
    },
    {
      "nombre": "Roca",
      "precio": 3000
    },
    {
      "nombre": "Roque Sáenz Peña",
      "precio": 3000
    },
    {
      "nombre": "San Martín",
      "precio": 3000
    },
    {
      "nombre": "Sarmiento",
      "precio": 3000
    },
    {
      "nombre": "Savio Norte",
      "precio": 5000
    },
    {
      "nombre": "Vélez Sarsfield",
      "precio": 3000
    }
  ]
};

const PRODUCTOS = [
  {
    "id": 3,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Dos corazones",
    "descripcion": "26g",
    "precio": 2000,
    "stock": 15,
    "imagen": "https://acdn-us.mitiendanube.com/stores/516/580/products/dos-corazones-11-332c34d60583c48b5316238715255399-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 4,
    "categoria": "BEBIDAS",
    "subcategoria": "FERNET",
    "nombre": "Fernet Branca 750cc",
    "descripcion": "",
    "precio": 20000,
    "stock": 6,
    "imagen": "https://gobar.vtexassets.com/arquivos/ids/155700/01010700006.jpg?v=636684849572070000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 6,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Chesterfield",
    "descripcion": "Etiqueta de 20",
    "precio": 4700,
    "stock": 4,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 7,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Marlboro Craft",
    "descripcion": "Etiqueta de 20",
    "precio": 5000,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 8,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Marlboro Craft Sandia",
    "descripcion": "Etiqueta de 20",
    "precio": 5000,
    "stock": 4,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 9,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Marlboro Craft Convertible",
    "descripcion": "Etiqueta de 20",
    "precio": 5000,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 10,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Chesterfield Uva",
    "descripcion": "Etiqueta de 20",
    "precio": 4700,
    "stock": 4,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 11,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Chesterfield Convertible",
    "descripcion": "Etiqueta de 20",
    "precio": 4700,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 12,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Phillip Morris Original",
    "descripcion": "Etiqueta de 20",
    "precio": 6500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 13,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Phillip Morris Convertible",
    "descripcion": "Etiqueta de 20",
    "precio": 6500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 14,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Phillip Morris Económico",
    "descripcion": "Etiqueta de 20",
    "precio": 3000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 15,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Master",
    "descripcion": "Etiqueta de 20",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 16,
    "categoria": "CIGARRILLO",
    "subcategoria": "",
    "nombre": "Melbourne",
    "descripcion": "Etiqueta de 20",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 17,
    "categoria": "BEBIDAS",
    "subcategoria": "FERNET",
    "nombre": "Fernet Branca 450cc",
    "descripcion": "",
    "precio": 14000,
    "stock": 0,
    "imagen": "https://gobar.vtexassets.com/arquivos/ids/155700/01010700006.jpg?v=636684849572070000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 18,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Fantoche Triple Negro",
    "descripcion": "",
    "precio": 1500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 19,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Fantoche Triple Blanco",
    "descripcion": "",
    "precio": 1500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 20,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Tatin Triple Blanco",
    "descripcion": "",
    "precio": 1500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 21,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Tatin Triple Negro",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 22,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Block",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 23,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Chocotorta",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 24,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Mini Torta Águila",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 25,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Mini Torta Blanca",
    "descripcion": "Águila",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 26,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Mini Torta Brownie",
    "descripcion": "Águila",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 27,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Alfajor BYN Negro",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 28,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Alfajor BYN Blanco",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 29,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Tofi Triple Negro",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 30,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Tofi Triple Blanco",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 31,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Bon o Bon Triple Blanco",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 32,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Bon o Bon Triple Negro",
    "descripcion": "",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 33,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Arroyito Bomba",
    "descripcion": "Triple",
    "precio": 5300,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 34,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Arroyito Dinamita",
    "descripcion": "Triple",
    "precio": 4500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 35,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Arroyito Molotov",
    "descripcion": "Triple",
    "precio": 4000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 36,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Arroyito Avellana",
    "descripcion": "Simple",
    "precio": 4000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 37,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Arroyito Pistacho",
    "descripcion": "Simple",
    "precio": 4000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 38,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Fantoche Super Triple Negro",
    "descripcion": "",
    "precio": 1700,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 39,
    "categoria": "ALFAJORES",
    "subcategoria": "",
    "nombre": "Fantoche Super Triple Red Velvet",
    "descripcion": "",
    "precio": 1700,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 40,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Miller Lata",
    "descripcion": "473cc",
    "precio": 3500,
    "stock": 0,
    "imagen": "https://ardiaprod.vtexassets.com/arquivos/ids/311015/Cerveza-Lata-Miller-473-Ml-_1.jpg?v=638599380961170000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 41,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Salta Cautiva Lata",
    "descripcion": "473cc",
    "precio": 2800,
    "stock": 0,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDeJ7gRhj8VKKBDU5MtIAqTeT0AFoJITDw4e-3rmo63NVBlpQqaFc3MXDO&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 42,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Imperial Golden Lata",
    "descripcion": "473cc",
    "precio": 3300,
    "stock": 0,
    "imagen": "https://statics.dinoonline.com.ar/imagenes/full_600x600_ma/3100836_f.jpg",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 43,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Imperial Ipa Lata",
    "descripcion": "473cc",
    "precio": 3300,
    "stock": 0,
    "imagen": "https://jumboargentina.vtexassets.com/arquivos/ids/891199/7793147570743.jpg?v=638996949721100000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 44,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Imperial Roja Lata",
    "descripcion": "473cc",
    "precio": 3300,
    "stock": 0,
    "imagen": "https://acdn-us.mitiendanube.com/stores/001/144/141/products/mesa-de-trabajo-214-10021-e07e2f0f098cbbf9b516706061970391-640-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 45,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Imperial Negra Lata",
    "descripcion": "473cc",
    "precio": 3300,
    "stock": 0,
    "imagen": "https://www.lacoopeencasa.coop/media/lcec/publico/articulos/b/e/6/be64a383a4c29048ae876f61ac5ef1c9",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 46,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Imperial Extra Lager Lata",
    "descripcion": "473cc",
    "precio": 3300,
    "stock": 0,
    "imagen": "https://www.lacoopeencasa.coop/media/lcec/publico/articulos/8/f/2/8f2e7cacb91ff0553567ca980c5a6e9e",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 47,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Santa Fe Lata",
    "descripcion": "473cc",
    "precio": 2500,
    "stock": 0,
    "imagen": "https://acdn-us.mitiendanube.com/stores/798/865/products/30277421-5b1322777c7a81aec816639271972748-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 48,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Schneider Lata",
    "descripcion": "473cc",
    "precio": 2700,
    "stock": 0,
    "imagen": "https://acdn-us.mitiendanube.com/stores/005/246/100/products/gemini_generated_image_m5fq9zm5fq9zm5fq-e3f02efe693bd6908617597822650233-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 49,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Schneider Latón",
    "descripcion": "710cc",
    "precio": 3800,
    "stock": 0,
    "imagen": "https://acdn-us.mitiendanube.com/stores/001/551/869/products/foto-tienda-nube-vito-1020-x-1020-px-94-399e2afe5275ce9ef717544976054463-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 50,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Heineken Lata",
    "descripcion": "473cc",
    "precio": 4300,
    "stock": 0,
    "imagen": "https://static.wixstatic.com/media/d2b1c5_f933b237be504a3bade1b7a34b3bc96f~mv2.png/v1/fill/w_480,h_480,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/d2b1c5_f933b237be504a3bade1b7a34b3bc96f~mv2.png",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 51,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Heineken Latón",
    "descripcion": "710cc",
    "precio": 6300,
    "stock": 0,
    "imagen": "https://static.wixstatic.com/media/d2b1c5_f933b237be504a3bade1b7a34b3bc96f~mv2.png/v1/fill/w_480,h_480,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/d2b1c5_f933b237be504a3bade1b7a34b3bc96f~mv2.png",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 52,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Brahma Latón",
    "descripcion": "710cc",
    "precio": 3600,
    "stock": 0,
    "imagen": "https://acdn-us.mitiendanube.com/stores/001/551/869/products/foto-tienda-nube-vito-1020-x-1020-px-91-d753cfbae131380f0b17544955111230-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 53,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Quilmes Latón",
    "descripcion": "710cc",
    "precio": 3200,
    "stock": 0,
    "imagen": "https://cepadevinos.com/wp-content/uploads/2021/01/7792798012923_02_nuevopack.jpg",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 54,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Stella Artois Latón",
    "descripcion": "710cc",
    "precio": 5400,
    "stock": 0,
    "imagen": "https://arcordiezb2c.vteximg.com.br/arquivos/ids/182764/Cerveza-Lager-Lata-Stella-Artois-710-Cc-1-18394.jpg?v=638460381712800000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 55,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Schneider 1L",
    "descripcion": "",
    "precio": 4600,
    "stock": 0,
    "imagen": "https://acdn-us.mitiendanube.com/stores/798/865/products/31270648-fed0d8f802c9f664d817026243412554-640-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 56,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Santa Fe 1L",
    "descripcion": "",
    "precio": 4300,
    "stock": 0,
    "imagen": "https://acdn-us.mitiendanube.com/stores/798/865/products/73673640-d827996fa10f94232d17738115132900-640-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 57,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Imperial Extra Lager 1L",
    "descripcion": "",
    "precio": 4800,
    "stock": 0,
    "imagen": "https://jumboargentina.vtexassets.com/arquivos/ids/903921/imperial.jpg?v=639111656130170000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 58,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Imperial Golden 1L",
    "descripcion": "",
    "precio": 5500,
    "stock": 0,
    "imagen": "https://jumboargentina.vtexassets.com/arquivos/ids/891212/7793147573720.jpg?v=638996954857900000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 59,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Heineken 1L",
    "descripcion": "",
    "precio": 7000,
    "stock": 0,
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_790546-MLA52349541271_112022-O.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 60,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Brahma 1L",
    "descripcion": "",
    "precio": 4200,
    "stock": 0,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSAtXJWvDp0sh3u_5nRPxAht9gAKIlPSX_wCB7SutL3g&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 61,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Cerveza Quilmes 1L",
    "descripcion": "",
    "precio": 4000,
    "stock": 0,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRywJELU-QXnkakJ1uWH3U_SBE883g9GJ7x8-aUoeDFpRWINvz1yBd3fv0&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 62,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Ferrero",
    "descripcion": "x4",
    "precio": 7000,
    "stock": 2,
    "imagen": "https://acdn-us.mitiendanube.com/stores/516/580/products/rocher-1x41-74e19fb0642024830416232644746256-640-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 63,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Ferrero",
    "descripcion": "x3",
    "precio": 4600,
    "stock": 2,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9rVPS-gc5a1F6FVYqXuY1i_5Vig5iymVgUlS5SoW1Y6bv2qMIkXOfO7-k&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 64,
    "categoria": "GOLOSINA",
    "subcategoria": "POSTRE DE MANÍ",
    "nombre": "Mantecol",
    "descripcion": "Lheritier",
    "precio": 2000,
    "stock": 4,
    "imagen": "https://acdn-us.mitiendanube.com/stores/006/912/754/products/d_819905-mla43783868952_102020-b-95cdee2587bcc69be917623754923951-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 65,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler de chocolina",
    "descripcion": "55g",
    "precio": 3500,
    "stock": 1,
    "imagen": "https://arcorencasa.com/wp-content/uploads/2025/05/20250506-10353.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 66,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler tableta",
    "descripcion": "De leche, 55g",
    "precio": 3600,
    "stock": 1,
    "imagen": "https://arcorencasa.com/wp-content/uploads/2025/05/20250506-10348.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 67,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler block",
    "descripcion": "38g",
    "precio": 2000,
    "stock": 2,
    "imagen": "https://www.rimoldimayorista.com.ar/datos/uploads/mod_catalogo/31308/cofler-block-6048f63e4ed87.jpg",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 68,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Oblea bon o bon",
    "descripcion": "Blanco, 30g",
    "precio": 1000,
    "stock": 2,
    "imagen": "https://www.lacoopeencasa.coop/media/lcec/publico/articulos/8/0/e/80e122a8d212e4e86d2c1b51ecdc7bf0",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 69,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Oblea bon o bon",
    "descripcion": "Negro, 30g",
    "precio": 1000,
    "stock": 0,
    "imagen": "https://arcorencasa.com/wp-content/uploads/2024/10/20241008-3465.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 70,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler aireado",
    "descripcion": "Mixto 55g",
    "precio": 3800,
    "stock": 4,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_r4SuvIa1TRSWT_lRRezyap-2eiZfzNP0y4LNYk_hVA&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 71,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler aireado",
    "descripcion": "Blanco, 55g",
    "precio": 3800,
    "stock": 3,
    "imagen": "https://arcorencasa.com/wp-content/uploads/2024/10/20241008-10337.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 72,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler aireado",
    "descripcion": "Almendras, 55g",
    "precio": 3800,
    "stock": 2,
    "imagen": "https://arcorencasa.com/wp-content/uploads/2024/10/20241008-10343.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 73,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler aireado",
    "descripcion": "Con leche, 55g",
    "precio": 3800,
    "stock": 1,
    "imagen": "https://www.lacoopeencasa.coop/media/lcec/publico/articulos/8/a/8/8a813b0ca27433121018c80ffc113132",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 74,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler tableta",
    "descripcion": "De leche 140g",
    "precio": 8000,
    "stock": 3,
    "imagen": "https://masonlineprod.vtexassets.com/arquivos/ids/206600-800-auto?v=637850834568570000&width=800&height=auto&aspect=true",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 75,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler tableta",
    "descripcion": "Almendra, 140g",
    "precio": 8000,
    "stock": 2,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCO0vr0UWboDQMC789Q2ITjzVb4tqAH2OTFuHmPvuwQ2OYKE4g2ux6WXI&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 76,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Cofler tableta",
    "descripcion": "Rocklets, 140g",
    "precio": 8000,
    "stock": 1,
    "imagen": "https://arjosimarprod.vtexassets.com/arquivos/ids/168606-800-auto?v=638536305682800000&width=800&height=auto&aspect=true",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 77,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Bocadito Marroc",
    "descripcion": "14g",
    "precio": 1500,
    "stock": 54,
    "imagen": "https://farmacityar.vtexassets.com/arquivos/ids/186461/51220_bocadito-marroc-x-14-gr_imagen-1.jpg?v=636976712331170000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 78,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Bon o bon",
    "descripcion": "Bombón de maní, chocolate negro, 15g",
    "precio": 600,
    "stock": 23,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz31YyERvjjOvehCurV6yFpR4h_bcf9cyB1jQBnj21fU_tnJGEj0wwQ6Da&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 79,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Huevo Kinder",
    "descripcion": "Huevo sorpresa, 20g",
    "precio": 5000,
    "stock": 8,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnbkICa8Hv19eSRpKsAUkEyR9TnviiQw7E1n3N9hGHJ-yTtLuwXEsjRek&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 80,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Rocklets",
    "descripcion": "20g",
    "precio": 600,
    "stock": 5,
    "imagen": "https://www.lacoopeencasa.coop/media/lcec/publico/articulos/e/2/e/e2e7af9fef893b4ba5b892c9c903b14d",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 81,
    "categoria": "GOLOSINA",
    "subcategoria": "PASTILLA",
    "nombre": "Yapa",
    "descripcion": "17g",
    "precio": 400,
    "stock": 3,
    "imagen": "https://acdn-us.mitiendanube.com/stores/003/079/899/products/la-yapa-uni-38d38089c4dffcc8ac17108889507564-480-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 82,
    "categoria": "GOLOSINA",
    "subcategoria": "PASTILLA",
    "nombre": "Mentitas",
    "descripcion": "26g",
    "precio": 500,
    "stock": 0,
    "imagen": "https://kioscodonluis.com.ar/common/files/producto/216/unnamed%20(8).jpg",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 83,
    "categoria": "GOLOSINA",
    "subcategoria": "PASTILLA",
    "nombre": "D.R.F",
    "descripcion": "De menta, 23g",
    "precio": 300,
    "stock": 0,
    "imagen": "https://jumboargentina.vtexassets.com/arquivos/ids/251800/Pastilla-De-Menta--Drf-12x-12x23gs-paq-gr-23-1-109236.jpg?v=636388577033500000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 84,
    "categoria": "GOLOSINA",
    "subcategoria": "CHUPETIN",
    "nombre": "Pico dulce",
    "descripcion": "14g",
    "precio": 500,
    "stock": 34,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgpNJkRduxMTPgC5AAYKh0nRT-uyn_2nLiLjvdfKppEZZ0Wprxt2Izozxx&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 85,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Paragüitas",
    "descripcion": "Felfort",
    "precio": 1000,
    "stock": 33,
    "imagen": "https://farmacityar.vtexassets.com/arquivos/ids/186463-800-auto?v=636976712338970000&width=800&height=auto&aspect=true",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 86,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Bananina",
    "descripcion": "Felfort, 15g",
    "precio": 700,
    "stock": 19,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7rj_pYjyQyXI-swkDkgCXLuYSgO-10pN1tyD06D-JsfzmuRTnRBtPT2nK&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 87,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Medallita de menta",
    "descripcion": "Felfort, 16g",
    "precio": 900,
    "stock": 19,
    "imagen": "https://acdn-us.mitiendanube.com/stores/001/167/320/products/mentita-fel-fort1-ee5e870f71870a858016448517714005-640-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 88,
    "categoria": "GOLOSINA",
    "subcategoria": "CHOCOLATE",
    "nombre": "Nutella B-ready",
    "descripcion": "Rellena de nutella, 22g",
    "precio": 2200,
    "stock": 9,
    "imagen": "https://acdn-us.mitiendanube.com/stores/006/912/754/products/06c5e3f6-02aa-4be2-ab83-a51332c36268-9d34ae2b5cdf8c720717740359155435-1024-1024.jpg",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 89,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Tubito max",
    "descripcion": "De ananá, 25g",
    "precio": 500,
    "stock": 13,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtQ5f-NT5r66_mNtzwh9ZKRPEBqEx38hcRWtl8g9tsOA&s",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 90,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Ositos",
    "descripcion": "Mogul, 30g",
    "precio": 600,
    "stock": 8,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg8Ck0bw_ewWe9tPeOG5OczDBikzQ1-6ZxC2gZoeQIOA&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 91,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Tiburones",
    "descripcion": "Mogul, 30g",
    "precio": 600,
    "stock": 6,
    "imagen": "https://arcorencasa.com/wp-content/uploads/2024/10/20241010-2001.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 92,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Moritas",
    "descripcion": "Mogul, 50g",
    "precio": 1000,
    "stock": 6,
    "imagen": "https://toledodigitalar.vtexassets.com/arquivos/ids/173783/30850.jpg?v=638796872151930000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 93,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Jelly bean",
    "descripcion": "Mogul Extreme, 50g",
    "precio": 1000,
    "stock": 7,
    "imagen": "https://kioskoboxoeste.com.ar/wp-content/uploads/2025/10/20251023_161638_0000.png",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 94,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Ositos acidos",
    "descripcion": "Mogul, 50g",
    "precio": 1000,
    "stock": 3,
    "imagen": "https://farmacityar.vtexassets.com/arquivos/ids/240097/161867_pastillas-de-goma-oso-extreme-x-55-gr_imagen-1.jpg?v=638163154655970000",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 95,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Palotes",
    "descripcion": "Limón y sandía, 50g",
    "precio": 1000,
    "stock": 6,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsaQ6Z1zg43Ox9L-kQ643CLi_LlpbGhPZd0pf53QJgpQ&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 96,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Touch",
    "descripcion": "Con alcohol, Caipiroska ácidas, 40g",
    "precio": 2300,
    "stock": 2,
    "imagen": "https://acdn-us.mitiendanube.com/stores/001/126/866/products/captura-de-pantalla-2025-10-14-161329-baddb9d0fd882e2a0417604693703175-640-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 97,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Touch",
    "descripcion": "Con alcohol, Maracuyá y Caipiroska aácidas, 40g",
    "precio": 2300,
    "stock": 2,
    "imagen": "https://acdn-us.mitiendanube.com/stores/006/547/835/products/foto-1-maracuya-18aae4a5bf33d7e40c17721299128873-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 98,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Touch",
    "descripcion": "Con alcohol, Piña colada, 40g",
    "precio": 2300,
    "stock": 2,
    "imagen": "https://acdn-us.mitiendanube.com/stores/006/547/835/products/foto-1-pina-9b8488a695b130379117721298283180-480-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 99,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Touch",
    "descripcion": "Con alcohol, Gin tonic, 40G",
    "precio": 2300,
    "stock": 2,
    "imagen": "https://acdn-us.mitiendanube.com/stores/001/126/866/products/captura-de-pantalla-2025-10-14-161045-0cebb60d4d2e77176717604693659807-640-0.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 100,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Anillitos frutales",
    "descripcion": "Gomitas, 50g",
    "precio": 1000,
    "stock": 12,
    "imagen": "https://acdn-us.mitiendanube.com/stores/002/975/549/products/diseno-sin-titulo-2023-08-29t152647-5821-92140ca1340a465d6a16933338723055-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 101,
    "categoria": "GOLOSINA",
    "subcategoria": "CARAMELO",
    "nombre": "Caramelo Masticable",
    "descripcion": "Masticable surtido Arcor, 26g",
    "precio": 1000,
    "stock": 9,
    "imagen": "https://acdn-us.mitiendanube.com/stores/326/260/products/screenshot_20250419_190914_chrome-616a48a8c7f286efd017451006211408-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 102,
    "categoria": "GOLOSINA",
    "subcategoria": "CARAMELO",
    "nombre": "Caramelo BC",
    "descripcion": "Sin azúcar, 29g",
    "precio": 1000,
    "stock": 7,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZEP-4SJJiCNTaSj-_44FNWxyqDaK1uSzpZJMpJrUxRHvUhD7JYDMz56I&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 103,
    "categoria": "GOLOSINA",
    "subcategoria": "CARAMELO",
    "nombre": "Caramelos frutales rellenos",
    "descripcion": "Caramelos Arcor, 46g",
    "precio": 1000,
    "stock": 5,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGqECvduJ1Xn1u1KFhElUgSbopiPL6iWBzRneONMtstmDjKyiiQvlrMdE8&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 104,
    "categoria": "GOLOSINA",
    "subcategoria": "CARAMELO",
    "nombre": "Rodajitas ácidas",
    "descripcion": "Arcor, 26g",
    "precio": 1000,
    "stock": 13,
    "imagen": "https://elgauchostore.com/wp-content/uploads/2025/08/Diseno-sin-titulo-2025-08-13T151843.647.jpg",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 105,
    "categoria": "GOLOSINA",
    "subcategoria": "CARAMELO",
    "nombre": "Gajo frutal",
    "descripcion": "Arcor, 52g",
    "precio": 1000,
    "stock": 10,
    "imagen": "https://dcdn-us.mitiendanube.com/stores/001/602/042/products/66b99a13-0880-4cf2-bfa5-c18f866b5feb_nube-24eb48d8a4ef78ecc516165523947968-1024-1024.webp",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 106,
    "categoria": "GOLOSINA",
    "subcategoria": "CARAMELO",
    "nombre": "Palote surtido",
    "descripcion": "Mogul extreme, 52g",
    "precio": 1000,
    "stock": 1,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCTLQyzeqZqDBNNVmGIa18jVxJv3Z3SlLjw8nwto5EOyqhmX_rKq0wNO8&s=10",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 107,
    "categoria": "GOLOSINA",
    "subcategoria": "GOMITAS",
    "nombre": "Frutillitas",
    "descripcion": "Arcor ácidas, 60g",
    "precio": 1000,
    "stock": 4,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq0-oAIf-PEAM0TbDYzi8fm2YWc4eBzCKYE8_IYtw28Q&s",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 108,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Oreo",
    "descripcion": "",
    "precio": 2000,
    "stock": 11,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 109,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Pepito",
    "descripcion": "",
    "precio": 2000,
    "stock": 8,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 110,
    "categoria": "GOLOSINA",
    "subcategoria": "MAGDALENA",
    "nombre": "Don Satur",
    "descripcion": "Vainilla Rellena dulce leche",
    "precio": 3000,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 111,
    "categoria": "GOLOSINA",
    "subcategoria": "MAGDALENA",
    "nombre": "Don Satur",
    "descripcion": "Chocolate con Dulce de leche",
    "precio": 3000,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 112,
    "categoria": "GOLOSINA",
    "subcategoria": "MAGDALENA",
    "nombre": "Don Datur",
    "descripcion": "Vainilla",
    "precio": 3000,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 113,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Cereal Mix",
    "descripcion": "Avena y Chips",
    "precio": 2500,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 114,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Galletita cofler",
    "descripcion": "Roclets",
    "precio": 2000,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 115,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Galletita cofler",
    "descripcion": "Block",
    "precio": 2000,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 116,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Corona 1L",
    "descripcion": "",
    "precio": 6000,
    "stock": 4,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 117,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Corona",
    "descripcion": "330cc",
    "precio": 3500,
    "stock": 6,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 118,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Corona 0% Alcohol",
    "descripcion": "330cc",
    "precio": 3500,
    "stock": 6,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 119,
    "categoria": "BEBIDAS",
    "subcategoria": "CERVEZAS",
    "nombre": "Stella Artois 0% Aalcohol",
    "descripcion": "473cc",
    "precio": 3500,
    "stock": 22,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 120,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Chocolinas",
    "descripcion": "250g",
    "precio": 2500,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 121,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Diversión Surtidas",
    "descripcion": "",
    "precio": 2500,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 122,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Sonrisas",
    "descripcion": "",
    "precio": 2000,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 123,
    "categoria": "GOLOSINA",
    "subcategoria": "GALLETITAS",
    "nombre": "Merengadas",
    "descripcion": "",
    "precio": 2000,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 124,
    "categoria": "ALMACEN",
    "subcategoria": "BICOCHITOS",
    "nombre": "Don Satur",
    "descripcion": "Tortita Negra",
    "precio": 1700,
    "stock": 4,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 125,
    "categoria": "ALMACEN",
    "subcategoria": "BICOCHITOS",
    "nombre": "Don Satur",
    "descripcion": "Dulces",
    "precio": 1700,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 126,
    "categoria": "ALMACEN",
    "subcategoria": "BICOCHITOS",
    "nombre": "Don Satur",
    "descripcion": "Salados",
    "precio": 1700,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 127,
    "categoria": "ALMACEN",
    "subcategoria": "TALITAS",
    "nombre": "Fermar",
    "descripcion": "",
    "precio": 2000,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 128,
    "categoria": "ALMACEN",
    "subcategoria": "TALITAS",
    "nombre": "Farmar",
    "descripcion": "Fajitas Con Lino",
    "precio": 2000,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 129,
    "categoria": "ALMACEN",
    "subcategoria": "TALITAS",
    "nombre": "Farmar",
    "descripcion": "Multi Cereal",
    "precio": 2000,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 130,
    "categoria": "SNACKS",
    "subcategoria": "QUENTO",
    "nombre": "Quento",
    "descripcion": "Mostaza",
    "precio": 2500,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 131,
    "categoria": "SNACKS",
    "subcategoria": "QUENTO",
    "nombre": "Quento",
    "descripcion": "Salame",
    "precio": 2500,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 132,
    "categoria": "SNACKS",
    "subcategoria": "QUENTO",
    "nombre": "Quento",
    "descripcion": "Clásicas",
    "precio": 2500,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 133,
    "categoria": "SNACKS",
    "subcategoria": "QUENTO",
    "nombre": "Quento",
    "descripcion": "Limon",
    "precio": 2500,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 134,
    "categoria": "SNACKS",
    "subcategoria": "QUENTO",
    "nombre": "Quento",
    "descripcion": "Cheddar",
    "precio": 2500,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 135,
    "categoria": "SNACKS",
    "subcategoria": "QUENTO",
    "nombre": "Quento",
    "descripcion": "Ketchup",
    "precio": 2500,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 136,
    "categoria": "SNACKS",
    "subcategoria": "QUENTO",
    "nombre": "Quento",
    "descripcion": "Nachos Sabor Queso",
    "precio": 2500,
    "stock": 3,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 137,
    "categoria": "SNACKS",
    "subcategoria": "SALADIX",
    "nombre": "Saladix Pizza",
    "descripcion": "100g",
    "precio": 1500,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 138,
    "categoria": "SNACKS",
    "subcategoria": "SALADIX",
    "nombre": "Saladix Jamón",
    "descripcion": "100G",
    "precio": 1500,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 139,
    "categoria": "SNACKS",
    "subcategoria": "SALADIX",
    "nombre": "Saladix Duo",
    "descripcion": "100g",
    "precio": 1500,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 140,
    "categoria": "SNACKS",
    "subcategoria": "SALADIX",
    "nombre": "Cross",
    "descripcion": "Sabor original",
    "precio": 100,
    "stock": 2,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 141,
    "categoria": "SNACKS",
    "subcategoria": "SALADIX",
    "nombre": "Cross",
    "descripcion": "Pizza",
    "precio": 1000,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 142,
    "categoria": "SNACKS",
    "subcategoria": "SUELTO",
    "nombre": "Maní",
    "descripcion": "Con Piel",
    "precio": 1000,
    "stock": 5,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 143,
    "categoria": "SNACKS",
    "subcategoria": "SUELTO",
    "nombre": "Maní",
    "descripcion": "Salado Sin Piel",
    "precio": 1000,
    "stock": 4,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 144,
    "categoria": "SNACKS",
    "subcategoria": "SUELTO",
    "nombre": "Maní Saborizado",
    "descripcion": "Pizza",
    "precio": 1000,
    "stock": 5,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 145,
    "categoria": "SNACKS",
    "subcategoria": "SUELTO",
    "nombre": "Maní saborizado",
    "descripcion": "Jamón",
    "precio": 1000,
    "stock": 5,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 146,
    "categoria": "BEBIDAS",
    "subcategoria": "FERNET",
    "nombre": "Fernet Buhero",
    "descripcion": "",
    "precio": 12000,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 147,
    "categoria": "BEBIDAS",
    "subcategoria": "FERNET",
    "nombre": "Fernet Buhero Mandelo",
    "descripcion": "Mandarina y Pomelo",
    "precio": 12000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 148,
    "categoria": "BEBIDAS",
    "subcategoria": "FERNET",
    "nombre": "Fernet 1882",
    "descripcion": "Lata 473cc",
    "precio": 2500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 149,
    "categoria": "BEBIDAS",
    "subcategoria": "FERNET",
    "nombre": "Fernet 1882",
    "descripcion": "750cc",
    "precio": 12000,
    "stock": 1,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 150,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Coca - Cola",
    "descripcion": "500cc",
    "precio": 2200,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 151,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Coca - Cola",
    "descripcion": "1,5L",
    "precio": 5000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 152,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Coca - Cola",
    "descripcion": "2,25L",
    "precio": 6800,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 153,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Coca - Cola",
    "descripcion": "Vidrio 1,25L Ret.",
    "precio": 3500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 154,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Coca - Cola",
    "descripcion": "Plastico Ret. 2L",
    "precio": 4500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 155,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Fanta",
    "descripcion": "500cc",
    "precio": 2200,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 156,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Coca - Cola",
    "descripcion": "Lata 330cc",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 157,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Sprite",
    "descripcion": "500cc",
    "precio": 2200,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 158,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Sprite",
    "descripcion": "1,5L",
    "precio": 5000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 159,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Sprite",
    "descripcion": "2,25L",
    "precio": 6800,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 160,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Sprite",
    "descripcion": "Vidrio 1,25L Ret",
    "precio": 3500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 161,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Sprite",
    "descripcion": "Plastico Ret. 2L",
    "precio": 4500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 162,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Sprite",
    "descripcion": "Lata 330cc",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 163,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Fanta",
    "descripcion": "1,5L",
    "precio": 5000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 164,
    "categoria": "BEBIDAS",
    "subcategoria": "GASEOSA",
    "nombre": "Fanta",
    "descripcion": "Lata 330cc",
    "precio": 2000,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 165,
    "categoria": "BEBIDAS",
    "subcategoria": "JUGOS",
    "nombre": "Cepita",
    "descripcion": "Botella 1L",
    "precio": 3500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 166,
    "categoria": "BEBIDAS",
    "subcategoria": "JUGOS",
    "nombre": "Cepita",
    "descripcion": "1L Caja",
    "precio": 3500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 167,
    "categoria": "BEBIDAS",
    "subcategoria": "JUGOS",
    "nombre": "Cepita",
    "descripcion": "Botellita 300cc",
    "precio": 1500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  },
  {
    "id": 168,
    "categoria": "BEBIDAS",
    "subcategoria": "JUGOS",
    "nombre": "Cepita",
    "descripcion": "Cajita 300cc",
    "precio": 1500,
    "stock": 0,
    "imagen": "",
    "esCombo": false,
    "productos": []
  }
];

const HISTORIAL = [];